version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-available:/etc/nginx/sites-available:ro
      - ./nginx_logs:/var/log/nginx
      - /var/www/html:/var/www/html
      - /etc/nginx/dist:/etc/nginx/dist
    restart: unless-stopped 